// <auto-generated />
using System;
using CodeKurs.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeKurs.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260314182930_MarkdownSeeding")]
    partial class MarkdownSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("CodeKurs.Web.Models.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Lessons");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            Description = "Ein Einstieg in die Welt von C#.",
                            Language = "csharp",
                            Order = 1,
                            Title = "C# Grundlagen"
                        });
                });

            modelBuilder.Entity("CodeKurs.Web.Models.ProgrammingTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChoicesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrectAnswer")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpectedOutput")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InitialCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("LessonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlaceholderDependency")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequiredKeywords")
                        .HasColumnType("TEXT");

                    b.Property<string>("TestCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1000,
                            Description = "C# ist eine objektorientierte Sprache von Microsoft.",
                            ExpectedOutput = "",
                            InitialCode = "",
                            Language = "csharp",
                            LessonId = 100,
                            Order = 1,
                            Title = "Was ist C#?",
                            Type = 0
                        },
                        new
                        {
                            Id = 1001,
                            Description = "Gib 'Hallo Welt!' aus.",
                            ExpectedOutput = "Hallo Welt!",
                            InitialCode = "using System;\n\npublic class Program\n{\n	public static void Main()\n	{\n		// Dein Code\n	}\n}",
                            Language = "csharp",
                            LessonId = 100,
                            Order = 2,
                            RequiredKeywords = "Console.WriteLine",
                            Title = "Hallo Welt",
                            Type = 1
                        });
                });

            modelBuilder.Entity("CodeKurs.Web.Models.UserProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastSubmittedCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<int>("TaskId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("Progress");
                });

            modelBuilder.Entity("CodeKurs.Web.Models.ProgrammingTask", b =>
                {
                    b.HasOne("CodeKurs.Web.Models.Lesson", "Lesson")
                        .WithMany("Tasks")
                        .HasForeignKey("LessonId");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("CodeKurs.Web.Models.UserProgress", b =>
                {
                    b.HasOne("CodeKurs.Web.Models.ProgrammingTask", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("CodeKurs.Web.Models.Lesson", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
