// <auto-generated />
using System;
using CodeKurs.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeKurs.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260314183112_CompleteMarkdownMigration")]
    partial class CompleteMarkdownMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("CodeKurs.Web.Models.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Lessons");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            Description = "<p>Lerne Java kennen.</p><p>Java ist eine plattformunabhängige Sprache.</p>\n",
                            Language = "java",
                            Order = 1,
                            Title = "Java Einstieg"
                        },
                        new
                        {
                            Id = 101,
                            Description = "<p>Lerne Entscheidungen im Code zu treffen.</p><p>In dieser Lektion lernst du <code>if</code> und <code>else</code> kennen.</p>\n",
                            Language = "csharp",
                            Order = 2,
                            Title = "Kontrollstrukturen"
                        },
                        new
                        {
                            Id = 102,
                            Description = "<p>Objektorientierte Programmierung.</p><p>Alles in C# findet in Klassen statt.</p>\n",
                            Language = "csharp",
                            Order = 4,
                            Title = "Klassen & Methoden"
                        },
                        new
                        {
                            Id = 103,
                            Description = "<p>Wiederhole Aufgaben effizient.</p><p>Schleifen helfen dir, Aufgaben mehrfach auszuführen.</p>\n",
                            Language = "csharp",
                            Order = 3,
                            Title = "Schleifen"
                        },
                        new
                        {
                            Id = 104,
                            Description = "<p>Ein Einstieg in die Welt von C#.</p><p>In dieser Lektion lernst du die ersten Schritte in C#.</p>\n",
                            Language = "csharp",
                            Order = 1,
                            Title = "C# Grundlagen"
                        },
                        new
                        {
                            Id = 105,
                            Description = "<p>Programmieren für das Web.</p><p>JavaScript erweckt Webseiten zum Leben.</p>\n",
                            Language = "javascript",
                            Order = 1,
                            Title = "JavaScript Einführung"
                        });
                });

            modelBuilder.Entity("CodeKurs.Web.Models.ProgrammingTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChoicesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrectAnswer")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpectedOutput")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InitialCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("LessonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlaceholderDependency")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequiredKeywords")
                        .HasColumnType("TEXT");

                    b.Property<string>("TestCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1000,
                            Description = "Schreibe 'Hallo Welt!' in Java.",
                            ExpectedOutput = "Hallo Welt!",
                            InitialCode = "public class Program {\n    public static void main(String[] args) {\n        // Dein Code hier\n    }\n}",
                            Language = "java",
                            LessonId = 100,
                            Order = 1,
                            RequiredKeywords = "System.out.println",
                            Title = "Java: Hallo Welt",
                            Type = 1
                        },
                        new
                        {
                            Id = 1001,
                            Description = "Prüfe, ob x (10) > 5 ist und gib 'Ja' aus.",
                            ExpectedOutput = "Ja",
                            InitialCode = "public class Program {\n    public static void main(String[] args) {\n        int x = 10;\n        // Dein Code hier\n    }\n}",
                            Language = "java",
                            LessonId = 100,
                            Order = 2,
                            RequiredKeywords = "if",
                            Title = "Java: If-Else",
                            Type = 1
                        },
                        new
                        {
                            Id = 1002,
                            Description = "Prüfe, ob die Variable 'zahl' positiv oder negativ ist. Gib 'Positiv' oder 'Negativ' aus.",
                            ExpectedOutput = "Negativ",
                            InitialCode = "using System;\n\npublic class Program\n{\n	public static void Main()\n	{\n		int zahl = -5;\n		// Dein Code hier\n	}\n}",
                            Language = "csharp",
                            LessonId = 101,
                            Order = 1,
                            RequiredKeywords = "if,else",
                            Title = "Logik: Positiv/Negativ",
                            Type = 1
                        },
                        new
                        {
                            Id = 1003,
                            Description = "Erstelle eine Klasse 'Calculator' mit einer statischen Methode 'Add(int a, int b)'.",
                            ExpectedOutput = "",
                            InitialCode = "public class Calculator \n{\n    // Hier deine Methode\n}",
                            Language = "csharp",
                            LessonId = 102,
                            Order = 1,
                            RequiredKeywords = "class,Calculator,static,int",
                            TestCode = "public class TestRunner {\n    public static void Main() {\n        if(Calculator.Add(5, 5) == 10 && Calculator.Add(-1, 1) == 0)\n            System.Console.WriteLine(\"SUCCESS_ALL_TESTS_PASSED\");\n        else\n            throw new System.Exception(\"Tests fehlgeschlagen.\");\n    }\n}",
                            Title = "Edu: Die Rechner-Klasse",
                            Type = 3
                        },
                        new
                        {
                            Id = 1004,
                            Description = "Berechne die Summe der Zahlen 1 bis 5.",
                            ExpectedOutput = "15",
                            InitialCode = "using System;\n\npublic class Program\n{\n	public static void Main()\n	{\n		int summe = 0;\n		// Nutze eine for-Schleife\n		Console.WriteLine(summe);\n	}\n}",
                            Language = "csharp",
                            LessonId = 103,
                            Order = 1,
                            RequiredKeywords = "for",
                            Title = "For-Schleife: Summe",
                            Type = 1
                        },
                        new
                        {
                            Id = 1005,
                            Description = "C# ist eine objektorientierte Sprache von Microsoft.",
                            ExpectedOutput = "",
                            InitialCode = "",
                            Language = "csharp",
                            LessonId = 104,
                            Order = 1,
                            Title = "Was ist C#?",
                            Type = 0
                        },
                        new
                        {
                            Id = 1006,
                            Description = "Gib 'Hallo Welt!' aus.",
                            ExpectedOutput = "Hallo Welt!",
                            InitialCode = "using System;\n\npublic class Program\n{\n	public static void Main()\n	{\n		// Dein Code\n	}\n}",
                            Language = "csharp",
                            LessonId = 104,
                            Order = 2,
                            RequiredKeywords = "Console.WriteLine",
                            Title = "Hallo Welt",
                            Type = 1
                        },
                        new
                        {
                            Id = 1007,
                            Description = "Schreibe 'Hallo Welt!' in JavaScript.",
                            ExpectedOutput = "Hallo Welt!",
                            InitialCode = "console.log();",
                            Language = "javascript",
                            LessonId = 105,
                            Order = 1,
                            RequiredKeywords = "console.log",
                            Title = "JS: Hallo Welt",
                            Type = 1
                        },
                        new
                        {
                            Id = 1008,
                            Description = "Erstelle eine Funktion 'begruessung', die 'Hallo' zurückgibt.",
                            ExpectedOutput = "Hallo",
                            InitialCode = "function begruessung() {\n    // Dein Code hier\n}\nconsole.log(begruessung());",
                            Language = "javascript",
                            LessonId = 105,
                            Order = 2,
                            RequiredKeywords = "function,return",
                            Title = "JS: Funktionen",
                            Type = 1
                        });
                });

            modelBuilder.Entity("CodeKurs.Web.Models.UserProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastSubmittedCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<int>("TaskId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("Progress");
                });

            modelBuilder.Entity("CodeKurs.Web.Models.ProgrammingTask", b =>
                {
                    b.HasOne("CodeKurs.Web.Models.Lesson", "Lesson")
                        .WithMany("Tasks")
                        .HasForeignKey("LessonId");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("CodeKurs.Web.Models.UserProgress", b =>
                {
                    b.HasOne("CodeKurs.Web.Models.ProgrammingTask", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("CodeKurs.Web.Models.Lesson", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
