// <auto-generated />
using System;
using CodeKurs.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeKurs.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260314060339_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("CodeKurs.Web.Models.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Lessons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Lerne die Grundlagen von C#.",
                            Language = "csharp",
                            Order = 1,
                            Title = "C# Einführung"
                        },
                        new
                        {
                            Id = 2,
                            Description = "If-Else und Logik.",
                            Language = "csharp",
                            Order = 2,
                            Title = "Kontrollstrukturen"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Wiederholungen in C#.",
                            Language = "csharp",
                            Order = 3,
                            Title = "Schleifen"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Logik in Klassen kapseln.",
                            Language = "csharp",
                            Order = 4,
                            Title = "Klassen & Methoden"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Lerne Java kennen.",
                            Language = "java",
                            Order = 5,
                            Title = "Java Einstieg"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Programmieren für das Web.",
                            Language = "javascript",
                            Order = 6,
                            Title = "JavaScript Einführung"
                        });
                });

            modelBuilder.Entity("CodeKurs.Web.Models.ProgrammingTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChoicesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrectAnswer")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpectedOutput")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InitialCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("LessonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlaceholderDependency")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequiredKeywords")
                        .HasColumnType("TEXT");

                    b.Property<string>("TestCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "C# ist eine moderne Programmiersprache von Microsoft.",
                            ExpectedOutput = "",
                            InitialCode = "",
                            Language = "csharp",
                            LessonId = 1,
                            Order = 1,
                            Title = "Theorie: Was ist C#?",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Description = "Schreibe 'Hallo Welt!' auf die Konsole.",
                            ExpectedOutput = "Hallo Welt!",
                            InitialCode = "using System;\n\npublic class Program\n{\n	public static void Main()\n	{\n		// Dein Code hier\n	}\n}",
                            Language = "csharp",
                            LessonId = 1,
                            Order = 2,
                            RequiredKeywords = "Console.WriteLine",
                            Title = "Hallo Welt (C#)",
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Erstelle 'alter' mit Wert 25.",
                            ExpectedOutput = "25",
                            InitialCode = "using System;\n\npublic class Program\n{\n	public static void Main()\n	{\n		// Dein Code hier\n	}\n}",
                            Language = "csharp",
                            LessonId = 1,
                            Order = 3,
                            RequiredKeywords = "int,alter",
                            Title = "Variablen: int",
                            Type = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "Prüfe, ob 'zahl' (-5) positiv ist.",
                            ExpectedOutput = "Negativ",
                            InitialCode = "using System;\n\npublic class Program\n{\n	public static void Main()\n	{\n		int zahl = -5;\n		// Dein Code hier\n	}\n}",
                            Language = "csharp",
                            LessonId = 2,
                            Order = 1,
                            RequiredKeywords = "if,else",
                            Title = "Logik: Positiv/Negativ",
                            Type = 1
                        },
                        new
                        {
                            Id = 5,
                            Description = "Berechne Summe 1-5.",
                            ExpectedOutput = "15",
                            InitialCode = "using System;\n\npublic class Program\n{\n	public static void Main()\n	{\n		int summe = 0;\n		// Nutze eine for-Schleife\n		Console.WriteLine(summe);\n	}\n}",
                            Language = "csharp",
                            LessonId = 3,
                            Order = 1,
                            RequiredKeywords = "for",
                            Title = "For-Schleife: Summe",
                            Type = 1
                        },
                        new
                        {
                            Id = 8,
                            Description = "Erstelle eine Klasse 'Calculator' mit einer statischen Methode 'Add(int a, int b)', die die Summe zurückgibt.",
                            ExpectedOutput = "",
                            InitialCode = "public class Calculator \n{\n    // Hier deine Methode\n}",
                            Language = "csharp",
                            LessonId = 4,
                            Order = 1,
                            RequiredKeywords = "class,Calculator,static,int",
                            TestCode = "public class TestRunner {\n    public static void Main() {\n        if(Calculator.Add(5, 5) == 10 && Calculator.Add(-1, 1) == 0)\n            System.Console.WriteLine(\"SUCCESS_ALL_TESTS_PASSED\");\n        else\n            throw new System.Exception(\"Tests fehlgeschlagen.\");\n    }\n}",
                            Title = "Edu: Die Rechner-Klasse",
                            Type = 3
                        },
                        new
                        {
                            Id = 9,
                            Description = "Erstelle eine Instanz der Klasse 'Person', setze den Namen auf 'Max' und gib das Objekt zurück.",
                            ExpectedOutput = "",
                            InitialCode = "public class Person {\n    public string Name { get; set; }\n}\n\npublic class Program {\n    public static Person CreatePerson() {\n        // Erstelle hier eine neue Person und setze den Namen\n        return null;\n    }\n}",
                            Language = "csharp",
                            LessonId = 4,
                            Order = 2,
                            RequiredKeywords = "new,Person,Max",
                            TestCode = "public class TestRunner {\n    public static void Main() {\n        var p = Program.CreatePerson();\n        if(p != null && p.Name == \"Max\")\n            System.Console.WriteLine(\"SUCCESS_ALL_TESTS_PASSED\");\n        else\n            throw new System.Exception(\"Der Name ist nicht 'Max' oder das Objekt wurde nicht erstellt.\");\n    }\n}",
                            Title = "Edu: Objekte erstellen",
                            Type = 3
                        },
                        new
                        {
                            Id = 6,
                            Description = "Schreibe 'Hallo Welt!' in Java.",
                            ExpectedOutput = "Hallo Welt!",
                            InitialCode = "public class Program {\n    public static void main(String[] args) {\n        // Dein Code hier\n    }\n}",
                            Language = "java",
                            LessonId = 5,
                            Order = 1,
                            RequiredKeywords = "System.out.println",
                            Title = "Java: Hallo Welt",
                            Type = 1
                        },
                        new
                        {
                            Id = 7,
                            Description = "Schreibe 'Hallo Welt!' in JavaScript.",
                            ExpectedOutput = "Hallo Welt!",
                            InitialCode = "console.log();",
                            Language = "javascript",
                            LessonId = 6,
                            Order = 1,
                            RequiredKeywords = "console.log",
                            Title = "JS: Hallo Welt",
                            Type = 1
                        });
                });

            modelBuilder.Entity("CodeKurs.Web.Models.UserProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastSubmittedCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<int>("TaskId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("Progress");
                });

            modelBuilder.Entity("CodeKurs.Web.Models.ProgrammingTask", b =>
                {
                    b.HasOne("CodeKurs.Web.Models.Lesson", "Lesson")
                        .WithMany("Tasks")
                        .HasForeignKey("LessonId");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("CodeKurs.Web.Models.UserProgress", b =>
                {
                    b.HasOne("CodeKurs.Web.Models.ProgrammingTask", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("CodeKurs.Web.Models.Lesson", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
