// <auto-generated />
using System;
using CodeKurs.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeKurs.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260315153318_AddMoreCourseContent")]
    partial class AddMoreCourseContent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("CodeKurs.Web.Models.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Lessons");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            Description = "<p>Entscheidungen treffen mit if und else.</p>",
                            Language = "javascript",
                            Order = 2,
                            Title = "JavaScript: Kontrollstrukturen"
                        },
                        new
                        {
                            Id = 101,
                            Description = "<p>Programmieren für das Web.</p><p>JavaScript erweckt Webseiten zum Leben.</p>\n",
                            Language = "javascript",
                            Order = 1,
                            Title = "JavaScript Einführung"
                        },
                        new
                        {
                            Id = 102,
                            Description = "<p>Entscheidungen treffen mit if und else.</p>",
                            Language = "go",
                            Order = 2,
                            Title = "Go: Kontrollstrukturen"
                        },
                        new
                        {
                            Id = 103,
                            Description = "<p>Ein Einstieg in die Welt von Go (Golang).</p><p>In dieser Lektion lernst du die ersten Schritte in Go. Go ist bekannt für seine starke Unterstützung von Nebenläufigkeit und seine schnelle Kompilierung.</p>\n",
                            Language = "go",
                            Order = 1,
                            Title = "Go Grundlagen"
                        },
                        new
                        {
                            Id = 104,
                            Description = "<p>Lerne Entscheidungen im Code zu treffen.</p><p>In dieser Lektion lernst du <code>if</code> und <code>else</code> kennen.</p>\n",
                            Language = "csharp",
                            Order = 2,
                            Title = "Kontrollstrukturen"
                        },
                        new
                        {
                            Id = 105,
                            Description = "<p>Wiederhole Aufgaben effizient.</p><p>Schleifen helfen dir, Aufgaben mehrfach auszuführen.</p>\n",
                            Language = "csharp",
                            Order = 3,
                            Title = "Schleifen"
                        },
                        new
                        {
                            Id = 106,
                            Description = "<p>Ein Einstieg in die Welt von C#.</p><p>In dieser Lektion lernst du die ersten Schritte in C#.</p>\n",
                            Language = "csharp",
                            Order = 1,
                            Title = "C# Grundlagen"
                        },
                        new
                        {
                            Id = 107,
                            Description = "<p>Objektorientierte Programmierung.</p><p>Alles in C# findet in Klassen statt.</p>\n",
                            Language = "csharp",
                            Order = 4,
                            Title = "Klassen & Methoden"
                        },
                        new
                        {
                            Id = 108,
                            Description = "<p>Entscheidungen treffen und Code wiederholen.</p><p>Kontrollstrukturen sind das Herzstück jeder Programmiersprache. In Rust gibt es neben <code>if</code> und <code>else</code> auch mächtige Schleifen-Konstrukte wie <code>loop</code>, <code>while</code> und <code>for</code>.</p>\n",
                            Language = "rust",
                            Order = 3,
                            Title = "Rust: Kontrollstrukturen"
                        },
                        new
                        {
                            Id = 109,
                            Description = "<p>Wie liest man Daten von der Tastatur in Rust ein?</p><p>Rust legt großen Wert auf Sicherheit. Daher ist die Standardeingabe etwas ausführlicher als in anderen Sprachen. Das Modul <code>std::io</code> bietet Zugriff auf die Funktionen, um von der Tastatur zu lesen.</p>\n",
                            Language = "rust",
                            Order = 2,
                            Title = "Rust: Ein- und Ausgabe"
                        },
                        new
                        {
                            Id = 110,
                            Description = "<p>Ein Einstieg in die Welt von Rust - Sicher, schnell und modern.</p><p>In dieser Lektion lernst du die ersten Schritte in Rust. Rust wird zunehmend für Systemsoftware, Webentwicklung (WebAssembly) und sicherheitskritische Anwendungen eingesetzt.</p>\n",
                            Language = "rust",
                            Order = 1,
                            Title = "Rust Grundlagen"
                        },
                        new
                        {
                            Id = 111,
                            Description = "<p>Entscheidungen treffen mit if und else.</p>",
                            Language = "cpp",
                            Order = 2,
                            Title = "C++: Kontrollstrukturen"
                        },
                        new
                        {
                            Id = 112,
                            Description = "<p>Ein Einstieg in die objektorientierte Programmierung mit C++.</p><p>In dieser Lektion lernst du die ersten Schritte in C++. C++ wird häufig für Systemsoftware, Spieleentwicklung, Treiber und Hochleistungsanwendungen verwendet.</p>\n",
                            Language = "cpp",
                            Order = 1,
                            Title = "C++ Grundlagen"
                        },
                        new
                        {
                            Id = 113,
                            Description = "<p>Entscheidungen treffen mit if und else.</p>",
                            Language = "php",
                            Order = 2,
                            Title = "PHP: Kontrollstrukturen"
                        },
                        new
                        {
                            Id = 114,
                            Description = "<p>Ein Einstieg in die serverseitige Programmierung mit PHP.</p><p>In dieser Lektion lernst du die Grundlagen von PHP kennen. PHP-Code wird auf dem Server ausgeführt und das Ergebnis wird als HTML an den Browser gesendet.</p>\n",
                            Language = "php",
                            Order = 1,
                            Title = "PHP Grundlagen"
                        },
                        new
                        {
                            Id = 115,
                            Description = "<p>Entscheidungen treffen mit if und else.</p>",
                            Language = "c",
                            Order = 2,
                            Title = "C: Kontrollstrukturen"
                        },
                        new
                        {
                            Id = 116,
                            Description = "<p>Ein Einstieg in die prozedurale Programmierung mit C.</p><p>In dieser Lektion lernst du die ersten Schritte in C. C bildet die Grundlage für viele moderne Sprachen wie C++, C# und Java.</p>\n",
                            Language = "c",
                            Order = 1,
                            Title = "C Grundlagen"
                        },
                        new
                        {
                            Id = 117,
                            Description = "<p>Lerne, wie du den Programmfluss steuerst.</p><p>Python nutzt Einrückungen, um Code-Blöcke zu definieren. Es gibt keine geschweiften Klammern <code>{}</code> wie in C# oder Java.</p>\n",
                            Language = "python",
                            Order = 2,
                            Title = "Python: Kontrollstrukturen"
                        },
                        new
                        {
                            Id = 118,
                            Description = "<p>Ein Einstieg in die Welt von Python.</p><p>In dieser Lektion lernst du die ersten Schritte in Python. Python wird häufig in der Webentwicklung, Datenanalyse und künstlichen Intelligenz verwendet.</p>\n",
                            Language = "python",
                            Order = 1,
                            Title = "Python Grundlagen"
                        },
                        new
                        {
                            Id = 119,
                            Description = "<p>Lerne Java kennen.</p><p>Java ist eine plattformunabhängige Sprache.</p>\n",
                            Language = "java",
                            Order = 1,
                            Title = "Java Einstieg"
                        },
                        new
                        {
                            Id = 120,
                            Description = "<p>Entscheidungen treffen mit if und else.</p>",
                            Language = "java",
                            Order = 2,
                            Title = "Java: Kontrollstrukturen"
                        });
                });

            modelBuilder.Entity("CodeKurs.Web.Models.ProgrammingTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChoicesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrectAnswer")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpectedOutput")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InitialCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("LessonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlaceholderDependency")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequiredKeywords")
                        .HasColumnType("TEXT");

                    b.Property<string>("Solution")
                        .HasColumnType("TEXT");

                    b.Property<string>("TestCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1000,
                            Description = "Prüfe, ob die Variable 'zahl' positiv oder negativ ist. Gib 'Positiv' oder 'Negativ' aus.",
                            ExpectedOutput = "Negativ",
                            InitialCode = "let zahl = -5;\n// Dein Code hier\n",
                            Language = "javascript",
                            LessonId = 100,
                            Order = 1,
                            RequiredKeywords = "if,else",
                            Solution = "let zahl = -5;\nif (zahl > 0) {\n    console.log(\"Positiv\");\n} else {\n    console.log(\"Negativ\");\n}\n",
                            Title = "Logik: Positiv/Negativ",
                            Type = 1
                        },
                        new
                        {
                            Id = 1001,
                            Description = "Schreibe 'Hallo Welt!' in JavaScript.",
                            ExpectedOutput = "Hallo Welt!",
                            InitialCode = "console.log();",
                            Language = "javascript",
                            LessonId = 101,
                            Order = 1,
                            RequiredKeywords = "console.log",
                            Solution = "console.log(\"Hallo Welt!\");",
                            Title = "JS: Hallo Welt",
                            Type = 1
                        },
                        new
                        {
                            Id = 1002,
                            Description = "Erstelle eine Funktion 'begruessung', die 'Hallo' zurückgibt.",
                            ExpectedOutput = "Hallo",
                            InitialCode = "function begruessung() {\n    // Dein Code hier\n}\nconsole.log(begruessung());",
                            Language = "javascript",
                            LessonId = 101,
                            Order = 2,
                            RequiredKeywords = "function,return",
                            Title = "JS: Funktionen",
                            Type = 1
                        },
                        new
                        {
                            Id = 1003,
                            Description = "Prüfe, ob die Variable 'zahl' positiv oder negativ ist. Gib 'Positiv' oder 'Negativ' aus.",
                            ExpectedOutput = "Negativ",
                            InitialCode = "package main\nimport \"fmt\"\nfunc main() {\n    zahl := -5\n    // Dein Code hier\n}\n",
                            Language = "go",
                            LessonId = 102,
                            Order = 1,
                            RequiredKeywords = "if,else",
                            Solution = "package main\nimport \"fmt\"\nfunc main() {\n    zahl := -5\n    if zahl > 0 {\n        fmt.Print(\"Positiv\")\n    } else {\n        fmt.Print(\"Negativ\")\n    }\n}\n",
                            Title = "Logik: Positiv/Negativ",
                            Type = 1
                        },
                        new
                        {
                            Id = 1004,
                            Description = "Go ist eine bei Google entwickelte Open-Source-Programmiersprache, die sich durch Effizienz und Einfachheit auszeichnet.",
                            ExpectedOutput = "",
                            InitialCode = "",
                            Language = "go",
                            LessonId = 103,
                            Order = 1,
                            Title = "Was ist Go?",
                            Type = 0
                        },
                        new
                        {
                            Id = 1005,
                            Description = "Gib 'Hallo Welt!' aus.",
                            ExpectedOutput = "Hallo Welt!",
                            InitialCode = "package main\n\nimport \"fmt\"\n\nfunc main() {\n    // Dein Code\n}\n",
                            Language = "go",
                            LessonId = 103,
                            Order = 2,
                            RequiredKeywords = "fmt.Println",
                            Solution = "package main\n\nimport \"fmt\"\n\nfunc main() {\n    fmt.Println(\"Hallo Welt!\")\n}\n",
                            Title = "Hallo Welt",
                            Type = 1
                        },
                        new
                        {
                            Id = 1006,
                            Description = "Prüfe, ob die Variable 'zahl' positiv oder negativ ist. Gib 'Positiv' oder 'Negativ' aus.",
                            ExpectedOutput = "Negativ",
                            InitialCode = "using System;\n\npublic class Program\n{\n	public static void Main()\n	{\n		int zahl = -5;\n		// Dein Code hier\n	}\n}",
                            Language = "csharp",
                            LessonId = 104,
                            Order = 1,
                            RequiredKeywords = "if,else",
                            Title = "Logik: Positiv/Negativ",
                            Type = 1
                        },
                        new
                        {
                            Id = 1007,
                            Description = "Berechne die Summe der Zahlen 1 bis 5.",
                            ExpectedOutput = "15",
                            InitialCode = "using System;\n\npublic class Program\n{\n	public static void Main()\n	{\n		int summe = 0;\n		// Nutze eine for-Schleife\n		Console.WriteLine(summe);\n	}\n}",
                            Language = "csharp",
                            LessonId = 105,
                            Order = 1,
                            RequiredKeywords = "for",
                            Title = "For-Schleife: Summe",
                            Type = 1
                        },
                        new
                        {
                            Id = 1008,
                            Description = "C# ist eine objektorientierte Sprache von Microsoft.",
                            ExpectedOutput = "",
                            InitialCode = "",
                            Language = "csharp",
                            LessonId = 106,
                            Order = 1,
                            Title = "Was ist C#?",
                            Type = 0
                        },
                        new
                        {
                            Id = 1009,
                            Description = "Gib 'Hallo Welt!' aus.",
                            ExpectedOutput = "Hallo Welt!",
                            InitialCode = "using System;\n\npublic class Program\n{\n	public static void Main()\n	{\n		// Dein Code\n	}\n}",
                            Language = "csharp",
                            LessonId = 106,
                            Order = 2,
                            RequiredKeywords = "Console.WriteLine",
                            Solution = "using System;\n\npublic class Program\n{\n	public static void Main()\n	{\n		Console.WriteLine(\"Hallo Welt!\");\n	}\n}",
                            Title = "Hallo Welt",
                            Type = 1
                        },
                        new
                        {
                            Id = 1010,
                            Description = "Erstelle eine Klasse 'Calculator' mit einer statischen Methode 'Add(int a, int b)'.",
                            ExpectedOutput = "",
                            InitialCode = "public class Calculator \n{\n    // Hier deine Methode\n}",
                            Language = "csharp",
                            LessonId = 107,
                            Order = 1,
                            RequiredKeywords = "class,Calculator,static,int",
                            TestCode = "public class TestRunner {\n    public static void Main() {\n        if(Calculator.Add(5, 5) == 10 && Calculator.Add(-1, 1) == 0)\n            System.Console.WriteLine(\"SUCCESS_ALL_TESTS_PASSED\");\n        else\n            throw new System.Exception(\"Tests fehlgeschlagen.\");\n    }\n}",
                            Title = "Edu: Die Rechner-Klasse",
                            Type = 3
                        },
                        new
                        {
                            Id = 1011,
                            Description = "Prüfe, ob die Zahl `x` größer als 10 ist. Gib 'Groß' aus, ansonsten 'Klein'.",
                            ExpectedOutput = "Groß",
                            InitialCode = "fn main() {\n    let x = 15;\n    // Dein Code hier\n}\n",
                            Language = "rust",
                            LessonId = 108,
                            Order = 1,
                            RequiredKeywords = "if,else",
                            Solution = "fn main() {\n    let x = 15;\n    if x > 10 {\n        println!(\"Groß\");\n    } else {\n        println!(\"Klein\");\n    }\n}\n",
                            Title = "Einfaches if/else",
                            Type = 1
                        },
                        new
                        {
                            Id = 1012,
                            Description = "Rust hat eine endlose Schleife namens `loop`. Nutze `break`, um sie zu verlassen, wenn `i` den Wert 5 erreicht hat. Gib `i` in jedem Durchgang aus.",
                            ExpectedOutput = "0\n1\n2\n3\n4\n5",
                            InitialCode = "fn main() {\n    let mut i = 0;\n    loop {\n        // Dein Code hier\n        i += 1;\n    }\n}\n",
                            Language = "rust",
                            LessonId = 108,
                            Order = 2,
                            RequiredKeywords = "loop,break",
                            Solution = "fn main() {\n    let mut i = 0;\n    loop {\n        println!(\"{}\", i);\n        if i == 5 {\n            break;\n        }\n        i += 1;\n    }\n}\n",
                            Title = "Die `loop` Schleife",
                            Type = 1
                        },
                        new
                        {
                            Id = 1013,
                            Description = "Nutze eine `while` Schleife, um die Zahlen von 3 bis 1 (herunterzählend) auszugeben.",
                            ExpectedOutput = "3\n2\n1",
                            InitialCode = "fn main() {\n    let mut n = 3;\n    // Dein Code hier\n}\n",
                            Language = "rust",
                            LessonId = 108,
                            Order = 3,
                            RequiredKeywords = "while",
                            Solution = "fn main() {\n    let mut n = 3;\n    while n > 0 {\n        println!(\"{}\", n);\n        n -= 1;\n    }\n}\n",
                            Title = "While Schleife",
                            Type = 1
                        },
                        new
                        {
                            Id = 1014,
                            ChoicesJson = "[\"Damit sie schneller geladen wird\", \"Weil sie standardmäßig unveränderbar ist und wir Text hineinschreiben wollen\", \"Um anzuzeigen, dass es ein String ist\", \"Das mut ist optional\"]",
                            CorrectAnswer = "Weil sie standardmäßig unveränderbar ist und wir Text hineinschreiben wollen",
                            Description = "Warum muss die Variable für die Eingabe mit `mut` deklariert werden (z.B. `let mut input`)?",
                            ExpectedOutput = "",
                            InitialCode = "",
                            Language = "rust",
                            LessonId = 109,
                            Order = 1,
                            Title = "Anatomie der Eingabe",
                            Type = 2
                        },
                        new
                        {
                            Id = 1015,
                            Description = "In Rust nutzt man `std::io::stdin()`, um Eingaben einzulesen. <br>Lies einen Namen von der Tastatur ein und gib 'Hallo [Name]!' aus. <br>Hinweis: Tippe in das Eingabefeld rechts das Wort 'Rust' ein, bevor du auf Ausführen klickst.",
                            ExpectedOutput = "Hallo Rust!",
                            InitialCode = "use std::io;\n\nfn main() {\n    let mut input = String::new(); // Erstellt einen Puffer\n    \n    // Deine Aufgabe: Nutze io::stdin().read_line(&mut input).unwrap();\n    \n    println!(\"Hallo {}!\", input.trim());\n}\n",
                            Language = "rust",
                            LessonId = 109,
                            Order = 2,
                            RequiredKeywords = "read_line",
                            Solution = "use std::io;\n\nfn main() {\n    let mut input = String::new();\n    io::stdin().read_line(&mut input).unwrap();\n    println!(\"Hallo {}!\", input.trim());\n}\n",
                            Title = "Einen String einlesen",
                            Type = 1
                        },
                        new
                        {
                            Id = 1016,
                            Description = "Lies eine Zahl von der Tastatur ein, verdopple sie und gib das Ergebnis aus. <br>Hinweis: Nutze `.trim().parse::<i32>().unwrap()`, um den String in eine Zahl zu wandeln. <br>Tippe die Zahl '21' in das Eingabefeld.",
                            ExpectedOutput = "Ergebnis: 42",
                            InitialCode = "use std::io;\n\nfn main() {\n    let mut input = String::new();\n    io::stdin().read_line(&mut input).unwrap();\n    \n    // Deine Aufgabe: Wandle 'input' in eine Zahl 'n' um\n    // let n: i32 = ...\n    \n    let ergebnis = n * 2;\n    println!(\"Ergebnis: {}\", ergebnis);\n}\n",
                            Language = "rust",
                            LessonId = 109,
                            Order = 2,
                            RequiredKeywords = "parse",
                            Solution = "use std::io;\n\nfn main() {\n    let mut input = String::new();\n    io::stdin().read_line(&mut input).unwrap();\n    let n: i32 = input.trim().parse().unwrap();\n    let ergebnis = n * 2;\n    println!(\"Ergebnis: {}\", ergebnis);\n}\n",
                            Title = "Zahl einlesen",
                            Type = 1
                        },
                        new
                        {
                            Id = 1017,
                            Description = "Lies zwei Zahlen nacheinander ein und gib deren Summe aus. <br>Wichtig: Das Eingabefeld unterstützt aktuell nur eine Zeile. Trenne deine beiden Zahlen im Eingabefeld mit einem Leerzeichen (z.B. '10 5').",
                            ExpectedOutput = "Summe: 15",
                            InitialCode = "use std::io;\n\nfn main() {\n    let mut input = String::new();\n    io::stdin().read_line(&mut input).unwrap();\n    \n    let mut parts = input.split_whitespace();\n    let a: i32 = parts.next().unwrap().parse().unwrap();\n    let b: i32 = parts.next().unwrap().parse().unwrap();\n    \n    println!(\"Summe: {}\", a + b);\n}\n",
                            Language = "rust",
                            LessonId = 109,
                            Order = 3,
                            RequiredKeywords = "split_whitespace",
                            Solution = "use std::io;\n\nfn main() {\n    let mut input = String::new();\n    io::stdin().read_line(&mut input).unwrap();\n    let mut parts = input.split_whitespace();\n    let a: i32 = parts.next().unwrap().parse().unwrap();\n    let b: i32 = parts.next().unwrap().parse().unwrap();\n    println!(\"Summe: {}\", a + b);\n}\n",
                            Title = "Zwei Zahlen addieren",
                            Type = 1
                        },
                        new
                        {
                            Id = 1018,
                            Description = "Rust ist eine moderne Systemprogrammiersprache, die sich auf Sicherheit, Geschwindigkeit und Nebenläufigkeit konzentriert. Besonders bekannt ist sie für ihr einzigartiges Konzept der 'Ownership', das Speicherfehler verhindert.",
                            ExpectedOutput = "",
                            InitialCode = "",
                            Language = "rust",
                            LessonId = 110,
                            Order = 1,
                            Title = "Was ist Rust?",
                            Type = 0
                        },
                        new
                        {
                            Id = 1019,
                            Description = "Gib 'Hallo Welt!' aus.",
                            ExpectedOutput = "Hallo Welt!",
                            InitialCode = "fn main() {\n    // Dein Code hier\n}\n",
                            Language = "rust",
                            LessonId = 110,
                            Order = 2,
                            RequiredKeywords = "println!",
                            Solution = "fn main() {\n    println!(\"Hallo Welt!\");\n}\n",
                            Title = "Hallo Welt",
                            Type = 1
                        },
                        new
                        {
                            Id = 1020,
                            Description = "Prüfe, ob die Variable 'zahl' positiv oder negativ ist. Gib 'Positiv' oder 'Negativ' aus.",
                            ExpectedOutput = "Negativ",
                            InitialCode = "#include <iostream>\nusing namespace std;\nint main() {\n    int zahl = -5;\n    // Dein Code hier\n    return 0;\n}\n",
                            Language = "cpp",
                            LessonId = 111,
                            Order = 1,
                            RequiredKeywords = "if,else",
                            Solution = "#include <iostream>\nusing namespace std;\nint main() {\n    int zahl = -5;\n    if (zahl > 0) {\n        cout << \"Positiv\";\n    } else {\n        cout << \"Negativ\";\n    }\n    return 0;\n}\n",
                            Title = "Logik: Positiv/Negativ",
                            Type = 1
                        },
                        new
                        {
                            Id = 1021,
                            Description = "C++ ist eine von Bjarne Stroustrup entwickelte Programmiersprache, die als Erweiterung der Sprache C entstand. Sie unterstützt verschiedene Programmierparadigmen wie die prozedurale und die objektorientierte Programmierung.",
                            ExpectedOutput = "",
                            InitialCode = "",
                            Language = "cpp",
                            LessonId = 112,
                            Order = 1,
                            Title = "Was ist C++?",
                            Type = 0
                        },
                        new
                        {
                            Id = 1022,
                            Description = "Gib 'Hallo Welt!' aus.",
                            ExpectedOutput = "Hallo Welt!",
                            InitialCode = "#include <iostream>\n\nint main() {\n    // Dein Code hier\n    return 0;\n}\n",
                            Language = "cpp",
                            LessonId = 112,
                            Order = 2,
                            RequiredKeywords = "cout",
                            Solution = "#include <iostream>\n\nint main() {\n    std::cout << \"Hallo Welt!\" << std::endl;\n    return 0;\n}\n",
                            Title = "Hallo Welt",
                            Type = 1
                        },
                        new
                        {
                            Id = 1023,
                            Description = "Prüfe, ob die Variable '$zahl' positiv oder negativ ist. Gib 'Positiv' oder 'Negativ' aus.",
                            ExpectedOutput = "Negativ",
                            InitialCode = "<?php\n$zahl = -5;\n// Dein Code hier\n?>\n",
                            Language = "php",
                            LessonId = 113,
                            Order = 1,
                            RequiredKeywords = "if,else",
                            Solution = "<?php\n$zahl = -5;\nif ($zahl > 0) {\n    echo \"Positiv\";\n} else {\n    echo \"Negativ\";\n}\n?>\n",
                            Title = "Logik: Positiv/Negativ",
                            Type = 1
                        },
                        new
                        {
                            Id = 1024,
                            Description = "PHP (Hypertext Preprocessor) ist eine weit verbreitete serverseitige Skriptsprache, die besonders für die Webentwicklung geeignet ist.",
                            ExpectedOutput = "",
                            InitialCode = "",
                            Language = "php",
                            LessonId = 114,
                            Order = 1,
                            Title = "Was ist PHP?",
                            Type = 0
                        },
                        new
                        {
                            Id = 1025,
                            Description = "Gib 'Hallo Welt!' aus.",
                            ExpectedOutput = "Hallo Welt!",
                            InitialCode = "<?php\n// Dein Code hier\n",
                            Language = "php",
                            LessonId = 114,
                            Order = 2,
                            RequiredKeywords = "echo",
                            Solution = "<?php\necho \"Hallo Welt!\";\n",
                            Title = "Hallo Welt",
                            Type = 1
                        },
                        new
                        {
                            Id = 1026,
                            Description = "Prüfe, ob die Variable 'zahl' positiv oder negativ ist. Gib 'Positiv' oder 'Negativ' aus.",
                            ExpectedOutput = "Negativ",
                            InitialCode = "#include <stdio.h>\nint main() {\n    int zahl = -5;\n    // Dein Code hier\n    return 0;\n}\n",
                            Language = "c",
                            LessonId = 115,
                            Order = 1,
                            RequiredKeywords = "if,else",
                            Solution = "#include <stdio.h>\nint main() {\n    int zahl = -5;\n    if (zahl > 0) {\n        printf(\"Positiv\");\n    } else {\n        printf(\"Negativ\");\n    }\n    return 0;\n}\n",
                            Title = "Logik: Positiv/Negativ",
                            Type = 1
                        },
                        new
                        {
                            Id = 1027,
                            Description = "C ist eine imperative und prozedurale Programmiersprache, die in den 1970er Jahren entwickelt wurde und bis heute für Betriebssysteme und hardwarenahe Software eingesetzt wird.",
                            ExpectedOutput = "",
                            InitialCode = "",
                            Language = "c",
                            LessonId = 116,
                            Order = 1,
                            Title = "Was ist C?",
                            Type = 0
                        },
                        new
                        {
                            Id = 1028,
                            Description = "Gib 'Hallo Welt!' aus.",
                            ExpectedOutput = "Hallo Welt!",
                            InitialCode = "#include <stdio.h>\n\nint main() {\n    // Dein Code hier\n    return 0;\n}\n",
                            Language = "c",
                            LessonId = 116,
                            Order = 2,
                            RequiredKeywords = "printf",
                            Solution = "#include <stdio.h>\n\nint main() {\n    printf(\"Hallo Welt!\\n\");\n    return 0;\n}\n",
                            Title = "Hallo Welt",
                            Type = 1
                        },
                        new
                        {
                            Id = 1029,
                            Description = "Prüfe, ob die Variable 'zahl' positiv oder negativ ist. Gib 'Positiv' oder 'Negativ' aus.",
                            ExpectedOutput = "Negativ",
                            InitialCode = "zahl = -5\n# Dein Code hier\n",
                            Language = "python",
                            LessonId = 117,
                            Order = 1,
                            RequiredKeywords = "if,else",
                            Solution = "zahl = -5\nif zahl > 0:\n    print(\"Positiv\")\nelse:\n    print(\"Negativ\")\n",
                            Title = "Logik: Positiv/Negativ",
                            Type = 1
                        },
                        new
                        {
                            Id = 1030,
                            Description = "Nutze eine `for`-Schleife und die `range()` Funktion, um die Zahlen 1, 2 und 3 auszugeben.",
                            ExpectedOutput = "1\n2\n3",
                            InitialCode = "# Nutze for i in range(1, 4):\n",
                            Language = "python",
                            LessonId = 117,
                            Order = 2,
                            RequiredKeywords = "for,in,range",
                            Solution = "for i in range(1, 4):\n    print(i)\n",
                            Title = "Zahlen von 1 bis 3 ausgeben",
                            Type = 1
                        },
                        new
                        {
                            Id = 1031,
                            Description = "Python ist eine interpretierte, höhere Programmiersprache, die für ihre einfache Lesbarkeit und Vielseitigkeit bekannt ist.",
                            ExpectedOutput = "",
                            InitialCode = "",
                            Language = "python",
                            LessonId = 118,
                            Order = 1,
                            Title = "Was ist Python?",
                            Type = 0
                        },
                        new
                        {
                            Id = 1032,
                            Description = "Gib 'Hallo Welt!' aus.",
                            ExpectedOutput = "Hallo Welt!",
                            InitialCode = "# Dein Code hier\n",
                            Language = "python",
                            LessonId = 118,
                            Order = 2,
                            RequiredKeywords = "print",
                            Solution = "print(\"Hallo Welt!\")\n",
                            Title = "Hallo Welt",
                            Type = 1
                        },
                        new
                        {
                            Id = 1033,
                            Description = "Schreibe 'Hallo Welt!' in Java.",
                            ExpectedOutput = "Hallo Welt!",
                            InitialCode = "public class Program {\n    public static void main(String[] args) {\n        // Dein Code hier\n    }\n}",
                            Language = "java",
                            LessonId = 119,
                            Order = 1,
                            RequiredKeywords = "System.out.println",
                            Solution = "public class Program {\n    public static void main(String[] args) {\n        System.out.println(\"Hallo Welt!\");\n    }\n}",
                            Title = "Java: Hallo Welt",
                            Type = 1
                        },
                        new
                        {
                            Id = 1034,
                            Description = "Prüfe, ob x (10) > 5 ist und gib 'Ja' aus.",
                            ExpectedOutput = "Ja",
                            InitialCode = "public class Program {\n    public static void main(String[] args) {\n        int x = 10;\n        // Dein Code hier\n    }\n}",
                            Language = "java",
                            LessonId = 119,
                            Order = 2,
                            RequiredKeywords = "if",
                            Title = "Java: If-Else",
                            Type = 1
                        },
                        new
                        {
                            Id = 1035,
                            Description = "Erstelle eine Methode 'add(int a, int b)', die die Summe zurückgibt. Diese soll in einer Klasse 'Calculator' liegen.",
                            ExpectedOutput = "SUCCESS_ALL_TESTS_PASSED",
                            InitialCode = "class Calculator {\n    // Deine Methode hier\n}",
                            Language = "java",
                            LessonId = 119,
                            Order = 3,
                            RequiredKeywords = "static,int",
                            Solution = "class Calculator {\n    public static int add(int a, int b) {\n        return a + b;\n    }\n}",
                            TestCode = "\npublic class Program {\n    public static void main(String[] args) {\n        if (Calculator.add(10, 5) == 15 && Calculator.add(-1, 1) == 0) {\n            System.out.println(\"SUCCESS_ALL_TESTS_PASSED\");\n        } else {\n            System.out.println(\"Tests fehlgeschlagen.\");\n        }\n    }\n}",
                            Title = "Java: Taschenrechner",
                            Type = 3
                        },
                        new
                        {
                            Id = 1036,
                            Description = "Prüfe, ob die Variable 'zahl' positiv oder negativ ist. Gib 'Positiv' oder 'Negativ' aus.",
                            ExpectedOutput = "Negativ",
                            InitialCode = "public class Program {\n    public static void main(String[] args) {\n        int zahl = -5;\n        // Dein Code hier\n    }\n}\n",
                            Language = "java",
                            LessonId = 120,
                            Order = 1,
                            RequiredKeywords = "if,else",
                            Solution = "public class Program {\n    public static void main(String[] args) {\n        int zahl = -5;\n        if (zahl > 0) {\n            System.out.print(\"Positiv\");\n        } else {\n            System.out.print(\"Negativ\");\n        }\n    }\n}\n",
                            Title = "Logik: Positiv/Negativ",
                            Type = 1
                        });
                });

            modelBuilder.Entity("CodeKurs.Web.Models.UserProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastSubmittedCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<int>("TaskId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("Progress");
                });

            modelBuilder.Entity("CodeKurs.Web.Models.ProgrammingTask", b =>
                {
                    b.HasOne("CodeKurs.Web.Models.Lesson", "Lesson")
                        .WithMany("Tasks")
                        .HasForeignKey("LessonId");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("CodeKurs.Web.Models.UserProgress", b =>
                {
                    b.HasOne("CodeKurs.Web.Models.ProgrammingTask", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("CodeKurs.Web.Models.Lesson", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
